// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArE5epSrgmV7Ekc3cWnJIpFZO3ySL_tSg',
    appId: '1:1095912487078:web:6c6e60c8fe172a59cf5c67',
    messagingSenderId: '1095912487078',
    projectId: 'minimal-social-95c77',
    authDomain: 'minimal-social-95c77.firebaseapp.com',
    storageBucket: 'minimal-social-95c77.firebasestorage.app',
    measurementId: 'G-6HLMCH2MPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYO29o8MZaPoPXmO3iDQ1BWgvRqQ1KMYE',
    appId: '1:1095912487078:android:bf93c6656e0ef417cf5c67',
    messagingSenderId: '1095912487078',
    projectId: 'minimal-social-95c77',
    storageBucket: 'minimal-social-95c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQdZejdS5h_pMsC_7F2XI3S1lTs5Q51jk',
    appId: '1:1095912487078:ios:a1b70f55f72de759cf5c67',
    messagingSenderId: '1095912487078',
    projectId: 'minimal-social-95c77',
    storageBucket: 'minimal-social-95c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQdZejdS5h_pMsC_7F2XI3S1lTs5Q51jk',
    appId: '1:1095912487078:ios:a1b70f55f72de759cf5c67',
    messagingSenderId: '1095912487078',
    projectId: 'minimal-social-95c77',
    storageBucket: 'minimal-social-95c77.firebasestorage.app',
    iosBundleId: 'com.example.flutterfire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArE5epSrgmV7Ekc3cWnJIpFZO3ySL_tSg',
    appId: '1:1095912487078:web:b00ca8deb51bfb84cf5c67',
    messagingSenderId: '1095912487078',
    projectId: 'minimal-social-95c77',
    authDomain: 'minimal-social-95c77.firebaseapp.com',
    storageBucket: 'minimal-social-95c77.firebasestorage.app',
    measurementId: 'G-XYW52707QS',
  );
}
